development:
    adapter: postgresql
    database: lss_development
    pool: 5
    timeout: 5000


test:
  adapter: postgresql
  database: lss_test
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  database: lss_production
  pool: 5
  timeout: 5000
